### ISSUE TITLE
Has the project stopped maintenance?

### ISSUE THREAD

**Issue by quickerlab** [Artanidos/AnimationMaker#8]
A question.
does the great project stopped maintenance?
So long since last commit.

thanks.

**Comment by Artanidos** [comment]
Hi

There are no feature requests and no known bugs so no need to commit changes.

Art

----- Ursprüngliche Nachricht -----
Von: "quicker" <notifications@github.com>
Gesendet: ‎17.‎04.‎2019 05:47
An: "Artanidos/AnimationMaker" <AnimationMaker@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [Artanidos/AnimationMaker] Has the project stopped maintenance? (#8)

A question.
does the great project stopped maintenance?
So long since last commit.
thanks.

**Comment by quickerlab** [comment]
The features in todo.txt seems interesting, such as "Add the ability to add sound and voices"
I'm also interesting in export to qml.

How to open the project in QtCreator? I encountered compilation error.
In main.c, can't find winmainwindow.h

**Comment by Artanidos** [comment]
Hi

Compile is only working on Linux at the moment. If you like to compile on other platforms you have to change the .pro files.

Yes sound would be nice but I don't have an idea how to do this yet ;)

QML could be easy.
Therefore you are invited to create a plugin.

I don't have the time to do that right now. And you are the only one with requests.
Maybe later.

Olaf

----- Ursprüngliche Nachricht -----
Von: "quicker" <notifications@github.com>
Gesendet: ‎17.‎04.‎2019 11:54
An: "Artanidos/AnimationMaker" <AnimationMaker@noreply.github.com>
Cc: "Olaf Japp" <japp.olaf@gmail.com>; "Comment" <comment@noreply.github.com>
Betreff: Re: [Artanidos/AnimationMaker] Has the project stopped maintenance?(#8)

The feature in todo.txt seems interesting, such as "Add the ability to add sound and voices"
I'm also interesting in export to qml.
How to open the project in QtCreator? I encountered compilation error.
In main.c, can't find winmainwindow.h
