### ISSUE TITLE
Qt platform plugin "xcb" issues in Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by strusberg** [Artanidos/AnimationMaker#9]
Hi, when I tried to run AppiImage in Ubuntu 16.04LTS report: The application failed to start because it could not find or load the Qt platform plugin "xcb". I have libx11-xcb1 installed.

**Comment by Artanidos** [comment]
Hi, I have just released a bug fix.
Can you please try it out.
Art

----- Ursprüngliche Nachricht -----
Von: "strusberg" <notifications@github.com>
Gesendet: ‎17.‎05.‎2019 18:02
An: "Artanidos/AnimationMaker" <AnimationMaker@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [Artanidos/AnimationMaker] Qt platform plugin "xcb" issues in Ubuntu16.04LTS (#9)

Hi, when I tried to run AppiImage in Ubuntu 16.04LTS report: The application failed to start because it could not find or load the Qt platform plugin "xcb". I have libx11-xcb1 installed.
